language: objective-c
osx_image: xcode8.2

before_install:
  - pod repo update --silent
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace Challenge.xcworkspace -scheme 'Challenge' -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=10.0' build test CODE_SIGN_IDENTITY=- | xcpretty -c